### ISSUE TITLE
msg_responder needs knowledge of the IP address associated with each msg

### ISSUE THREAD

**Issue by sarnold** [freepn/fpnd#13]
This is required for both (internal) node ID/addr matching and f2b regex matching in the logs.  Currently the msg_responder is a separate (and very simple) daemon that only does the following:

* validates msg size and hex format
* logs the msg (node ID) or an error

  * if valid msg, return response str (msg), else log error msg

The msg_responder uses the responder service interface so the (source) IP addr is not currently visible for logging.  From the fpnd side we can see both the IP addr and node ID in the peer data, BUT we currently allow "late" node msgs with no extra validation.

**Comment by sarnold** [comment]
The fix:

* modify msg_responder.py so the IP addr of the msg sender is available for logging inside the ``echo()`` function

**Comment by sarnold** [comment]
After the next push, the new branch will have a list of candidate leaf nodes that could send a msg; example is a list of just one:

```
2020-02-14 03:27:16 UTC peerstate.main +73: DEBUG [10454] Collected leaf nodes: [{'2cce2db2e1': '192.168.0.54'}]
```

Now msg_responder needs an IP to go with the msg to match against the above list.

**Comment by ian-bateman** [comment]
This issue is currently blocked by the upstream nanomsg issue: https://github.com/nanomsg/nanomsg/issues/432

Blocked and marking as Shelved until further notice - will need to address this when we eventually upgrade to nng or similar.

**Comment by sarnold** [comment]
This is fixed in current master, at least as much as we can with the upstream nanomsg issue still open.

**Comment by sarnold** [comment]
Closing as "resolved" for the current prototype architecture.
