### ISSUE TITLE
script is in "failed" state on reboot / startup in bionic

### ISSUE THREAD

**Issue by ian-bateman** [freepn/fpnd#41]
When you start up a box with fpnd installed (on bionic ubuntu 18.04 LTS), the output of `systemctl status fpnd.service` is 'failed'. In order for the service run properly, it needs to be stopped and then started again. The service should not be in 'failed' state on startup; it should require manually being started, not start on boot.

**Comment by sarnold** [comment]
This should be fixed in the following packages; note focal pkgs are not affected:

* fpnd_0.8.9-3ubuntu1
* fpnd-0.8.9-3ubuntu0.18.04.1

**Comment by ian-bateman** [comment]
Issue Resolved.
