### ISSUE TITLE
fpnd and freepn-gtk3-tray should be bundled in .deb (PPA) packages

### ISSUE THREAD

**Issue by ian-bateman** [freepn/fpnd#44]
There should be 2 installation options for fpnd:

- fpnd-only (this is just the 'base' fpnd configuration option - useful for things like raspi's, servers, etc.)

- fpnd-and-freepn-gtk3-tray (this would be a 'bundled' installation option, such that both the UI and it's underlying packages are installed at the same time - useful (and expected behavior) for most desktop-environments / desktop Linux users)

**Comment by sarnold** [comment]
A couple of them are still "pending" but each PPA series on launchpad has a new revision ``0.0.2-2*`` with a runtime dependency on the ``python3-fpnd`` package; in this case the package name is ``freepn-gtk3-indicator``.

https://launchpad.net/~nerdboy/+archive/ubuntu/embedded

```
Format: 1.8
Date: Tue, 30 Jun 2020 17:42:12 -0700
Source: freepn-gtk3-tray
Architecture: source
Version: 0.0.2-2ubuntu0.20.04.1
Distribution: focal
Urgency: medium
Maintainer: Stephen L Arnold <nerdboy@gentoo.org>
Changed-By: Stephen L Arnold <nerdboy@gentoo.org>
Changes:
 freepn-gtk3-tray (0.0.2-2ubuntu0.20.04.1) focal; urgency=medium
 .
   * add python3-fpnd to runtime depends
```
