### ISSUE TITLE
Controller node log file needs to be smaller & needs to be rotated.

### ISSUE THREAD

**Issue by ian-bateman** [freepn/fpnd#45]
Log file on controller node is currently 9.65 GB - for obvious reasons this is too large to be useful.

Issue seen on Ubuntu 18.04 LTS

**Comment by sarnold** [comment]
The logrotate config gets installed but still depends on logrotate actually being installed on the target system (which it usually is).  In this case the config was getting installed by the `.ebuild` packages but was *not* installed by the `.deb` packages.  Also the log path is changed by the recent systemd service file updates, so both log paths are now in the config *and*  the latest `.deb` revisions install it.

The first one below is for openrc, the second one is systemd:

```
$ cat /etc/logrotate.d/fpnd 
/var/log/fpnd.log {
        compress
        daily
        rotate 7
        missingok
        copytruncate
}

/var/log/fpnd/fpnd.log {
        compress
        daily
        rotate 7
        missingok
        copytruncate
}
```
