### ISSUE TITLE
Feature/Enhancement: Raspi

### ISSUE THREAD

**Issue by mciverza** [freepn/fpnd#81]
Good day

Can I assist in helping add Raspi CLi support?
use case:  headless Raspi as a VPN routing node to add more nodes cheaply

Is there anything specific that would need to be done?  Python should be fine on Armv7, but I haven't looked closer to see if there are any platform specific network calls.

**Comment by sarnold** [comment]
I wouldn't recommend anything less than a 64-bit pi (rpi2 v1.2 or rpi3) and even then USB, mmc interface, and RAM can all be a bottleneck.  That said, I *do* test occasionally on some 1GB rpi3s, and the Mate image works *okay* but it's definitely not as reliable as say, an old ``snow`` chromebook or a nanopi-k2.

Headless should work fine, but right now I can only test on "supported" Ubuntu images (bionic and focal) and not raspbian.  If you're going to use one of the official Ubuntu cloud images, you probably want to disable things like cloud-init and snap (both of which can be *really* annoying resource hogs on a slow rpi.

Anyway, somewhere in a README there should be a blurb like this:

If you really don't want/need a desktop, you can still install the network component:

* Gentoo - ``sudo emerge net-misc/fpnd``
* Ubuntu - ``sudo apt-get install python3-fpnd``

**Comment by mciverza** [comment]
Thanks @sarnold
